### ISSUE TITLE
.

### ISSUE THREAD

**Issue by geronimopacis** [shalzuth/AutoGunfireReborn#10]

**Comment by mq003at** [comment]
Run the game first, then run the injector.

**Comment by geronimopacis** [comment]
Still doesn't work. I've tried that, that's actually the only way you would use this.

**Comment by BrendanatorX** [comment]
Works for me..

**Comment by geronimopacis** [comment]
> Works for me..

Really? Dang, I can't get this to work. It used to work before on my other PC. I guess something on my end doesn't allow it to work. Unfortunate.
