### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by geronimopacis** [shalzuth/AutoGunfireReborn#3]
Do you have a tutorial for noobs like me? Hehe, sounds interesting. Anyways, great work. Would love to be able to test it out one day

**Comment by shalzuth** [comment]
https://github.com/shalzuth/AutoGunfireReborn/releases/download/v1.0/GunfireRebornMods.exe

**Comment by weberlu88** [comment]
Hi! Which folder should I put the .exe file in?
I place the .exe file under "...\steamapps\common\Gunfire Reborn", and there's errors occured.
The error message is like: 
![螢幕擷取畫面 2021-07-17 200133](https://user-images.githubusercontent.com/43847259/126036380-489a68b6-3917-4bef-b24c-a94728e609e8.png)

**Comment by geronimopacis** [comment]
> https://github.com/shalzuth/AutoGunfireReborn/releases/download/v1.0/GunfireRebornMods.exe

Thank you man!

**Comment by shalzuth** [comment]
> Hi! Which folder should I put the .exe file in?
> I place the .exe file under "...\steamapps\common\Gunfire Reborn", and there's errors occured.
> The error message is like:
> ![螢幕擷取畫面 2021-07-17 200133](https://user-images.githubusercontent.com/43847259/126036380-489a68b6-3917-4bef-b24c-a94728e609e8.png)

It doesn’t need to be anywhere specific. Make sure the game is running first.

**Comment by weberlu88** [comment]
Thanks for the notice, the mod works perfectly now.
