### ISSUE TITLE
Could you provide some simple instructions on how to build from source

### ISSUE THREAD

**Issue by LogonDev** [shalzuth/AutoGunfireReborn#6]
Hi I pulled the repo using git clone:
git clone --recurse-submodules -j8 git@github.com:shalzuth/AutoGunfireReborn.git

I them set IL2CPPDumper as the default project and dumped the dlls into a DummyDLL folder but I am a bit confused where to go from here 

Thanks in advance

**Comment by shalzuth** [comment]
GunfireRebornDumper generates the DLL's using Il2cpp dumper, set GunfireRebornDumper as the default project. It will dump the dummy dlls, then create the proxy dlls.

**Comment by LogonDev** [comment]
Thanks
