### ISSUE TITLE
Crash on injection

### ISSUE THREAD

**Issue by chrion02** [shalzuth/AutoGunfireReborn#7]
I get this error on injection: https://prnt.sc/1i09xgj

**Comment by baoc2** [comment]
Same, my game just keeps crashing on injection since the latest update

**Comment by shalzuth** [comment]
Yes, need to redump the dll's every patch since unhollower uses method tokens now instead of name ref (or force unhollower to ignore the tokens)
The latest release.exe fixes this, need to push a new commit to match it still.

**Comment by baoc2** [comment]
> Yes, need to redump the dll's every patch since unhollower uses method tokens now instead of name ref (or force unhollower to ignore the tokens)
> The latest release.exe fixes this, need to push a new commit to match it still.

I think currently there's a little glitch to it such that aimbot would somehow switch off randomly midgame and there's no way to turn it back on other than actually restart the mod with the game.
Is there anyway to fix that issue?
Anyways, thanks for keeping the mods up to date man, it's such a great work!
